### ISSUE TITLE
Filesystem API might need a rework for Linux

### ISSUE THREAD

**Issue by JJL772** [quiverteam/Engine#55]
Naturally, Valve's hyper intelligent engineers used `WIN32_FILE_SEARCH` (or whatever it's called) structures in the actual exposed filesystem interface. Once again, two methods to handling this:
* Define the structure on Linux and continue implementing
* Screw win32 stuff! I wanna rewrite it!

**Comment by ACBob** [comment]
I like the `Screw win32`.
Who likes it, anyway?
